version: '3'

services:
  config-server:
    container_name: config-server
    image: alphawolfsforce/friends-config-server:develop
    environment:
      PORT: 3000
      API_GATEWAY_URI: http://localhost:4000/
      AUTH_SERVICE_URI: http://localhost:4000/
    ports: 
      - 5000:3000
 
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 8443:8443
      - 80:80
    volumes:
      - ./nginx.dev:/etc/nginx/conf.d
    depends_on:
      - config-server